// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqtpjxlxktjoqsqpepiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxdHBqeGx4a3Rqb3FzcXBlcGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTM5NTksImV4cCI6MjA3MDEyOTk1OX0.S55IJ8BogkLet5Lrv4MyJXIyZ3eRiCICEFm0WBm8kDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);